baseURL = "https://ecoindica.com/"
languageCode = "en-us"
title = "Economic Indicators"
theme = ["hugo-chart", "beautifulhugo"]
tags = ["blog"]
features = ["blog"]

googleAnalytics = "G-31C4PJYWFE"

SectionPagesMenu = "main"


[params]
    description = "[Click for Articles](https://ecoindica.com/post/)"
    githubUsername = "#"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"




