baseURL = "https://ecoindica.com/"
languageCode = "en-us"
title = "Economic Indicators (Beta)"
theme = "gohugo-theme-ananke"
tags = ["blog"]
features = ["blog"]

googleAnalytics = "G-31C4PJYWFE"

SectionPagesMenu = "main"






